# Generated by Django 3.2.8 on 2021-12-23 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Article Title')),
                ('author', models.CharField(max_length=120, verbose_name='Author(s)')),
                ('content', models.FilePathField()),
                ('date_added', models.DateTimeField(verbose_name='Date Published')),
                ('category', models.CharField(max_length=60, verbose_name='Category')),
                ('tags', models.TextField(blank=True)),
                ('photos', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=120, verbose_name='First Name')),
                ('l_name', models.CharField(max_length=120, verbose_name='Last Name')),
                ('address', models.CharField(max_length=300, verbose_name='Address')),
                ('city', models.CharField(max_length=120, verbose_name='City')),
                ('country', models.CharField(max_length=120, verbose_name='Country')),
                ('zip_code', models.IntegerField(max_length=10, verbose_name='Zip Code')),
                ('phone', models.IntegerField(max_length=20, verbose_name='Phone Number')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
        ),
    ]
