# Generated by Django 3.2.8 on 2021-12-23 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aspp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='photos',
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.IntegerField(verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='zip_code',
            field=models.IntegerField(verbose_name='Zip Code'),
        ),
    ]
