# Generated by Django 3.2.8 on 2021-12-23 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aspp', '0002_auto_20211223_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.FilePathField(verbose_name='File Path'),
        ),
    ]
