# Generated by Django 3.2.8 on 2021-12-23 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aspp', '0003_alter_article_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.FilePathField(blank=True, null=True, verbose_name='File Path'),
        ),
    ]
