# Generated by Django 3.2.8 on 2021-12-23 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aspp', '0004_alter_article_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='content',
        ),
    ]
