# Generated by Django 3.2.8 on 2021-12-23 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aspp', '0005_remove_article_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content',
            field=models.FilePathField(null=True, path=None, verbose_name='File Path'),
        ),
    ]
