# Generated by Django 3.2.8 on 2021-12-23 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aspp', '0006_article_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.FileField(null=True, upload_to='', verbose_name='Content'),
        ),
    ]
